import {
  RefreshCw,
  Workflow,
  Cable,
  BrainCircuit,
  Boxes,
  BarChart3,
  Code2,
  Database,
  Gauge,
  ShieldCheck,
  Truck,
  ShoppingCart,
  Factory,
  Landmark,
  HeartPulse,
  Building2,
  Clock,
  BadgeCheck,
  MapPin,
  Zap,
  Lock,
  Users,
  Rocket,
  Globe,
  Sparkles,
  Layers,
  Plug,
  Server,
  GitBranch,
  MessageSquare,
  FileCheck,
  Smartphone,
  ShoppingBag,
  PenTool,
  Cloud,
  Handshake,
  Headset,
  GraduationCap,
  Wheat,
  Bus,
  Search,
  Command,
  Mail,
  Home,
  Copy,
  type LucideIcon,
} from "lucide-react";

// Íconos con significado (reemplazan los antiguos "cuadrados de puntos").
const MAP: Record<string, LucideIcon> = {
  // soluciones (por id)
  moderniza: RefreshCw,
  automatiza: Workflow,
  integra: Cable,
  ia: BrainCircuit,
  productos: Boxes,
  datos: BarChart3,
  // servicios (por icon key)
  dev: Code2,
  link: Cable,
  ai: BrainCircuit,
  data: Database,
  dash: Gauge,
  shield: ShieldCheck,
  spark: Workflow,
  // industrias (por id)
  logistica: Truck,
  retail: ShoppingCart,
  manufactura: Factory,
  finanzas: Landmark,
  salud: HeartPulse,
  gobierno: Building2,
  educacion: GraduationCap,
  energia: Zap,
  agro: Wheat,
  transporte: Bus,
  search: Search,
  command: Command,
  mail: Mail,
  home: Home,
  copy: Copy,
  // extra (secciones nuevas)
  clock: Clock,
  badge: BadgeCheck,
  map: MapPin,
  zap: Zap,
  lock: Lock,
  users: Users,
  rocket: Rocket,
  globe: Globe,
  sparkles: Sparkles,
  layers: Layers,
  plug: Plug,
  server: Server,
  branch: GitBranch,
  message: MessageSquare,
  filecheck: FileCheck,
  mobile: Smartphone,
  ecommerce: ShoppingBag,
  design: PenTool,
  cloud: Cloud,
  handshake: Handshake,
  support: Headset,
};

export function Icon({
  name,
  className = "",
  strokeWidth = 1.6,
}: {
  name: string;
  className?: string;
  strokeWidth?: number;
}) {
  const Cmp = MAP[name] ?? Boxes;
  return <Cmp className={className} strokeWidth={strokeWidth} aria-hidden="true" />;
}
